version: '2'
services:
    serveus-app:
        image: serveus
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://serveus-mysql:3306/serveus?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    serveus-mysql:
        extends:
            file: mysql.yml
            service: serveus-mysql
